### ISSUE TITLE
Unexpected value 'CoolLocalStorage' exported by the module 'CoolStorageModule'

### ISSUE THREAD

**Issue by Calderis** [Hacklone/angular2-cool-storage#1]
Hi, I was trying your module and after following your README i got this error : 

`Unexpected value 'CoolLocalStorage' exported by the module 'CoolStorageModule'`

Do you know what could make this error happen ?

systemjs.config.js

```
System.config({
  ...
    map: {
      ...
      'angular2-cool-storage': 'npm:angular2-cool-storage'
    },
    packages: {
      ...
      'angular2-cool-storage': {
        main: './index.js',
        defaultExtension: 'js'
      }
    }
  });
```

app.component.ts

```
import { Component } from '@angular/core';
import { CoolLocalStorage } from 'angular2-cool-storage';


@Component({
  selector: 'my-app',
  templateUrl: 'app/views/app/app.component.html'
})
export class AppComponent {
    constructor(private localStorage: CoolLocalStorage){}
    public my_test:string = this.localStorage.getItem("my_test");
}
```

 and of curse the same app.module.ts that you specified in README.

**Comment by Hacklone** [comment]
Hey, 

The latest version should fix this issue. Could you try it out?

Thanks,
Barna

**Comment by Bosper** [comment]
Hello, I have same issue like Issue creator. Newest versions doesn't solve problem I use v. 1.1.0

**Comment by kashban** [comment]
This is an issue with the aot compiler (ngc) of ionic 2. See here for a more detailed explanation: 

https://github.com/driftyco/ionic-app-scripts/issues/145

**Comment by Hacklone** [comment]
Is this issue still active with the 1.2.0 release?

**Comment by TLmaK0** [comment]
Hi, with 1.2.0 I don't have this error at build time. But I get a new one when run the app:

```
node_modules\@angular\core\src\reflection\reflection_capabilities.js:61 Uncaught TypeError: ctorParameters.map is not a function
```

coming back to 1.1.0 works without error, but I can't build :).

I'm using angular@2.1.1

**Comment by Hacklone** [comment]
I cannot reproduce it :( can you create a plunkr or something? Maybe it's caused by something else. :)

**Comment by TLmaK0** [comment]
I was unable to reproduce it with a blank project, so forget my comment. Thanks!!

**Comment by Hacklone** [comment]
Fixed in version 1.2.0

**Comment by RathodGirish** [comment]
I am still getting problem 'CoolLocalStorage' is not exported by angular2-cool-storage
version : 1.2.0
